compute_program: "/main/test.cp"
constants {
  name: "color"
  type: CONSTANT_TYPE_USER
  value {
    x: 1.0
    y: 0.0
    z: 1.0
    w: 0.0
  }
}
samplers {
  name: "texture_in"
  wrap_u: WRAP_MODE_REPEAT
  wrap_v: WRAP_MODE_REPEAT
  filter_min: FILTER_MODE_MIN_LINEAR
  filter_mag: FILTER_MODE_MAG_LINEAR
  max_anisotropy: 0.0
  texture: ""
  name_hash: 0
}
samplers {
  name: "texture_out"
  wrap_u: WRAP_MODE_REPEAT
  wrap_v: WRAP_MODE_REPEAT
  filter_min: FILTER_MODE_MIN_NEAREST
  filter_mag: FILTER_MODE_MAG_NEAREST
  max_anisotropy: 0.0
  texture: ""
  name_hash: 0
}
