go.property("input", resource.texture())

function init(self)
	local t_backing = resource.create_texture("/my_backing_texture.texturec", {
		type   = graphics.TEXTURE_TYPE_IMAGE_2D,
		width  = 128,
		height = 128,
		format = graphics.TEXTURE_FORMAT_RGBA32F,
		flags  = graphics.TEXTURE_USAGE_FLAG_STORAGE + graphics.TEXTURE_USAGE_FLAG_SAMPLE,
	})

	local textures = {
		backing = resource.get_texture_info(t_backing).handle,
		input = resource.get_texture_info(self.input).handle
	}

	pprint(textures)

	msg.post("@render:", "add_textures", textures)
end
